services:
  - type: web
    name: private-dj-radio
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
